service: social-app
frameworkVersion: '3.0.0-pre.b463d7e2'

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline
custom:
  serverless-offline:
    host: 0.0.0.0
    noAuth: true
provider:
  # deploymentBucket:
  #   name: ${env:AWS_DEPLOYMENT_BUCKET_NAME}
  #   serverSideEncryption: AES256
  name: aws
  runtime: nodejs14.x
  # region: ${env:REGION}
  lambdaHashingVersion: 20201221
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
            - s3:ListBucket
functions:
  authorizerFunc:
    handler: controllers/authorizer.default
  profileCreate:
    handler: controllers/profile.profileCreate
    events:
      - httpApi:
          method: post
          path: /profiles
          authorizer: authorizerFunc
  profileGet:
    handler: controllers/profile.profileGet
    events:
      - httpApi:
          method: get
          path: /profiles/{profileId}
          authorizer: authorizerFunc
  profilesGet:
    handler: controllers/profile.profilesGet
    events:
      - httpApi:
          method: get
          path: /profiles
          authorizer: authorizerFunc
  profileUpdate:
    handler: controllers/profile.profileUpdate
    events:
      - httpApi:
          method: put
          path: /profiles/{profileId}
          authorizer: authorizerFunc
  profileRemove:
    handler: controllers/profile.profileRemove
    events:
      - httpApi:
          method: delete
          path: /profiles/{profileId}
          authorizer: authorizerFunc
