// eslint-disable-next-line
const { compile } = require('json-schema-to-typescript');
const fs = require('fs');
const user = require('../schema/user');

const allSchema = {
  ...user,
};
const schemaKeys = Object.keys(allSchema);

const bannerComment = `
/* eslint-disable */
/*
tslint:disable
This file was automatically generated by json-schema-to-typescript.
DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
and run json-schema-to-typescript to regenerate this file.
*/
`;

schemaKeys.forEach((schemaKey) => {
  const jsonSchema = allSchema[schemaKey];
  compile(jsonSchema, schemaKey, { bannerComment }).then((ts) => {
    if (!fs.existsSync('generated')) fs.mkdirSync('generated');
    if (!fs.existsSync('generated/types')) {
      fs.mkdirSync('generated/types');
    }
    fs.writeFileSync(`generated/types/${schemaKey}.ts`, ts);
  });
});
